// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1Lgnzb9xEnsuc66wl5JG1o3jEhx6x3U',
    appId: '1:886955799197:web:7912727d258a9644d4da74',
    messagingSenderId: '886955799197',
    projectId: 'aeapamsctutc',
    authDomain: 'aeapamsctutc.firebaseapp.com',
    storageBucket: 'aeapamsctutc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OOgUHIp8XrcvnBFLG8kR252cWByxJkc',
    appId: '1:886955799197:android:1e26f7091d999c59d4da74',
    messagingSenderId: '886955799197',
    projectId: 'aeapamsctutc',
    storageBucket: 'aeapamsctutc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJrkJjffIkQNhr5YGNg3sLoHkSlnAuUY',
    appId: '1:886955799197:ios:1eed5e2d057c2cb9d4da74',
    messagingSenderId: '886955799197',
    projectId: 'aeapamsctutc',
    storageBucket: 'aeapamsctutc.firebasestorage.app',
    iosBundleId: 'com.example.aeapamsctutc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJrkJjffIkQNhr5YGNg3sLoHkSlnAuUY',
    appId: '1:886955799197:ios:1eed5e2d057c2cb9d4da74',
    messagingSenderId: '886955799197',
    projectId: 'aeapamsctutc',
    storageBucket: 'aeapamsctutc.firebasestorage.app',
    iosBundleId: 'com.example.aeapamsctutc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1Lgnzb9xEnsuc66wl5JG1o3jEhx6x3U',
    appId: '1:886955799197:web:ea30461206068168d4da74',
    messagingSenderId: '886955799197',
    projectId: 'aeapamsctutc',
    authDomain: 'aeapamsctutc.firebaseapp.com',
    storageBucket: 'aeapamsctutc.firebasestorage.app',
  );
}
